### ISSUE TITLE
Move images to assets/images and update references

### ISSUE THREAD

**Issue by nick-verida** [verida/tech-capabilities-demo#38]
Images in the `public/media` folder need to be moved to the `src/assets/images` folder and references to them in the markdown files need to be updated. 

This should work both locally and in our deployed environment.

**Comment by cmcWebCode40** [comment]
> Images in the `public/media` folder need to be moved to the `src/assets/images` folder and references to them in the markdown files need to be updated.
> 
> This should work both locally and in our deployed environment.

@nick-verida  Regarding the issue with loading images in the markdown, I have tried to load from `src/assets/images` but it seems not to be working, I did test a Vue app deployed on netlify loading images from the `/public` folder and it worked.  see example [markdown](https://blissful-stonebraker-5190a0.netlify.app/)

could there be another workaround for this?

**Comment by nick-verida** [comment]
After taking a deeper look at this it appears the rewrites are case sensitive on AWS.

I've updated the rule to allow `.PNG` to work, but there are some markdown files that reference lower case images when the images are upper case. 

Please update all images to use a lower case extension and update the markdown files to all use lowercase too.

**Comment by cmcWebCode40** [comment]
> After taking a deeper look at this it appears the rewrites are case sensitive on AWS.
> 
> I've updated the rule to allow `.PNG` to work, but there are some markdown files that reference lower case images when the images are upper case.
> 
> Please update all images to use a lower case extension and update the markdown files to all use lowercase too.

ok noted I will do that

**Comment by nick-verida** [comment]
This didn't work. 

It looked like it did because the Mac file system is case preserving but insensitive, so `.png` and `.PNG` behave the same. See https://apple.stackexchange.com/a/22304

The change for the correctly updated the `.md` files to use lowercase, but didn't rename the files themselves: https://github.com/verida/tech-capabilities-demo/pull/41/commits/e169b9337fa6a25c8021b04803a0d226edfad340

See https://github.com/verida/tech-capabilities-demo/tree/develop/public/media (all `.PNG` files should be `.png`)
