### ISSUE TITLE
Feedback 9 Nov

### ISSUE THREAD

**Issue by tahpot** [verida/tech-capabilities-demo#44]
This is looking really awesome.

I do have some fussy feedback though :)

- Should we give this some sort of name? "Tech capabilities demo" sounds really bland
- I was getting confused by the content. I kept wanting to click on and engage with the screenshots. Even after I realised what was going, I clicked on the next page and automatically tried to interact again.
- Perhaps we need to lead with a short demo video show casing how it works rather than a wall of text? Or perhaps put the code you can play with at the very top and then go into detail explaining how it works?
- The code is too verbose to be useful. As a new user, I'm not going to get much value out of a 100 line code snippet where the only relevant piece of code is on line 76-80. All that bootstrapping needs to be hidden from the user so the relevant code is the only thing visible.
- We need a bright message / notification at the top of the page that says this is alpha and to contact us if you want access to the Vault.

Separately, sending a message didn't work for me. I tested sending a message to the same account via the web sandbox and it worked fine.

This was my error in JS console:

```Error during service worker registration: 
Error {}
2
The user denied permission to access the database.
Unknown error occurred with replication snapshot from remote database: test_db (https://ve4f1a770646de73eb71b00bad385a0ac471be2168ed34ab9f2640d75fd82dc18:d68a13731cac81d4274544a88e6a771c6c49e8fa6f6d3c079909915fac2fe45f@db.testnet.verida.io:5984)
```

**Comment by cmcWebCode40** [comment]
@tahpot, When tested send message demo, did you try to disconnect from the connect demo and login again ?

**Comment by tahpot** [comment]
@cmcWebCode40 No. 

I just tried again:

- Signed into the `connect` demo
- Navigated to `send message` demo
- Clicked `Send message`
- Entered `test` in the message box
- UI says `message sent`, however there are JS console errors and no message in the Vault

**Comment by cmcWebCode40** [comment]
ok thanks for the feedback , i will investigate

**Comment by nick-verida** [comment]
Rebranding as learn.verida.io

https://github.com/verida/tech-capabilities-demo/issues/47

**Comment by nick-verida** [comment]
Rearrange screens: https://github.com/verida/tech-capabilities-demo/issues/50

**Comment by nick-verida** [comment]
I can't replicate the issues with sending a message either. I successfully sent one with no console errors.

I tried a number of combinations of reloading of both the vault and the page.
