### ISSUE TITLE
Update footer to include Verida links as per main site

### ISSUE THREAD

**Issue by ryank000** [verida/tech-capabilities-demo#56]
I suggest we update the Verida Learn footer to include the link structure that exists on the main page - whilst keeping the colour styling of the Learn sub-site.

**Comment by cmcWebCode40** [comment]
@ryan do you mean we update the footer using this link style on the main page?


<img width="1114" alt="Screenshot 2021-11-17 at 05 11 48" src="https://user-images.githubusercontent.com/54280620/142133496-f4dc2517-c3d2-42b9-aa60-58505de90c02.png">

**Comment by ryank000** [comment]
Actually the inclusion of the Footer like we already have on the main webpage at verida.io
![image](https://user-images.githubusercontent.com/26591121/142144302-5f2565d9-bd6e-4aa0-82cf-5b6c895c7987.png)

**Comment by cmcWebCode40** [comment]
ok , thanks
